POST http://127.0.0.1:8000/api/v1/auth/registrar
Accept: application/json
content-type: application/json

{
    "name": "Andres Criollo",
    "email": "andres@info.com",
    "password": "andres1234"
}